name: build-node-js

on: ["push", "pull_request"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 5.0.x
      - name: Install dependencies
        run: |
            yarn install --frozen-lockfile
            cd test
            yarn install --frozen-lockfile
      - name: Run tests
        run: |
            yarn run compile
            cd test
            yarn run gulp preflight
            yarn run gulp run
            cd ..