name: build-node-js

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
  COVERALLS_GIT_COMMIT: ${{ github.sha }}
  COVERALLS_GIT_BRANCH: ${{ github.ref }}
  COVERALLS_SERVICE_NAME: github
jobs:
  build:

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 16.x]
        dotnet-version: ['5.0.x']
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: |
            yarn install --frozen-lockfile
            cd test
            yarn install --frozen-lockfile
      - name: Run tests
        run: |
            yarn run compile
            cd test
            yarn run gulp preflight
            yarn run gulp run
            cd ..
      - name: Coveralls
        run: |
            yarn run cover